version: '3.8'

services:
  devcontainer:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      - ../../:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taxonomy
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local